### ISSUE TITLE
Problem with PNP MBBT4403 on 5V motherboard

### ISSUE THREAD

**Issue by rico500** [Bioreactor/Bioreactor_v4#12]
Problem: Malfunctioning or inappropriate transistor.

![issue_mbbt4403](https://cloud.githubusercontent.com/assets/3426517/17082551/e3725732-5182-11e6-817b-6500ec6afac3.png)

Consequence: Weight cell is underpowered, therefor the measured values of the weight are inconsistent or stay constant. 

Observations: the emitter receives 4.7V (almost 5V so OK) the base receives 4.3V (also OK according to datasheet) the collector emits 0.4V (not OK) although the weight cell needs 5V. 

Quick Fix: remove transistor. The weight cell will be powered with analog 5V instead of digital 5V so measuring errors may appear.

**Comment by qcabrol** [comment]
Issue aleready referenced by #7 with more details
