### ISSUE TITLE
Check SST025 memory library

### ISSUE THREAD

**Issue by lpatiny** [Bioreactor/Bioreactor_v4#17]
Add dynamic ID check to know the capacity and be sure you can write more than one byte at a time. Some memory are quite limited at this level.

Change the library to allow a port as parameter.

**Comment by qcabrol** [comment]
S25FL116K 16 Mbit (2 MB) ? /Cypress
S25FL132K 32 Mbit (4 MB) ? /Cypress
S25FL164K 64 Mbit (8 MB) ? /Cypress
SST26VF064A/B : JEDEC = BF 26 43, mutiple bytes write : YES
SST25VF064C :    JEDEC = BF 25 4B, mutiple bytes write : YES
SST25VF032B :    JEDEC = BF 25 4A, mutiple bytes write : NO --> need to add support

1) check JEDEC to determine memory size and type
2) change writeLog implementation for 32B
3) add support for all memories of the family
