### ISSUE TITLE
mk3 heatbed allows to skip the aluminium plate

### ISSUE THREAD

**Issue by lpatiny** [Bioreactor/Bioreactor_v4#30]
The mk3 heatbed has directly an aluminium plate on the top so it simplify the design (just need to fill with silicon 6 holes).
It should cost around $15.
The design may have to be slightly changed in order to directly use this plate.

**Comment by apatru** [comment]
Design CAD v4.3 is parametered in the spreadsheet around the dimension of the new mk3 heatbed
