### ISSUE TITLE
PWM on peristaltic pump

### ISSUE THREAD

**Issue by lpatiny** [Bioreactor/Bioreactor_v4#32]
Are the pins for the peristaltic pump on PWM ? If not it would be nice.

**Comment by qcabrol** [comment]
change pin allocation to D5* and D10*, take care of providing a updated pin mapping

**Comment by qcabrol** [comment]
ref to 592270b3922a94a716772beb6e81ae62c0b9f190

**Comment by qcabrol** [comment]
Pin mapping is changed, Arduino Code needs to be changed as well
