### ISSUE TITLE
Change holes for Load cells on the CAD

### ISSUE THREAD

**Issue by qcabrol** [Bioreactor/Bioreactor_v4#38]
one of the holes has to be oblong to make the design compatible with more than one load cell type

**Comment by apatru** [comment]
The oblong hole would be weakening the structure as the weight of the bioreactor is on the 3 loading cells. Looking for alternative in the design such as parametrization of the hole size and placement

**Comment by apatru** [comment]
The CAD skteches are linked to a spreadsheet allowing to make the changes very easily without going through the whole dimensions on FreeCAD. Comments are available for the other type of loading cell
