### ISSUE TITLE
Program Thread for DRV8811 Stepper Driver

### ISSUE THREAD

**Issue by lpatiny** [Bioreactor/Bioreactor_v4#47]
Seems a stepper driver could be useful to reduce the noise level.

Based on : http://ebldc.com/?p=187 this could be achieved by increasing the Switching Frequency to something between 30 to 50 khz and using the following driver :

http://www.ti.com/lit/ds/symlink/drv8811.pdf

**Comment by qcabrol** [comment]
http://r6500.blogspot.ch/2014/12/fast-pwm-on-arduino-leonardo.html

Fast PWM : single slope on timer 1 can go as high as 31kHz with a 8MHz crystal MCU

**Comment by lpatiny** [comment]
Control of the current seems that it can also reduce the noise and the heat of the stepper

**Comment by lpatiny** [comment]
D9 seems the perfect candidate for the driver. See also https://github.com/Bioreactor/Bioreactor_v4/issues/59

**Comment by qcabrol** [comment]
Stepper driver is tester and functional. Proper stepper thread to be implemented

**Comment by tseesen** [comment]
Proper stepper thread has been implemented. Stepper is now functionnal on las version
