### ISSUE TITLE
Agitation : magnet and other

### ISSUE THREAD

**Issue by lpatiny** [Bioreactor/Bioreactor_v4#49]
Size of the magnet ?

Design of the plastic element on the stepper. Add a screw (printable ?). Plastic screw ?

**Comment by apatru** [comment]
3D printing tests in progress. cheap printers to avoid, test with resine

**Comment by apatru** [comment]
ref 24b4ebc029cd9f19624b51e0eb320208dc19a97e

**Comment by apatru** [comment]
ref 24c1f9e246ae8de5f9419efb0de1bea9745fda67

**Comment by apatru** [comment]
design final - to be printed with formlab 2 if possible
