### ISSUE TITLE
Reduce thickness of the tanks alu foundation

### ISSUE THREAD

**Issue by apatru** [Bioreactor/Bioreactor_v4#56]
The alu used in v4.2 is 10mm thick hence resulting into heat inertia and less accurate control. Next test to make 6mm with 2mm groove to plexi cylinder insertion

**Comment by qcabrol** [comment]
closed by commit aaa745561679a6480747b0850593fa2c41f0cdc9

**Comment by qcabrol** [comment]
closed by commit aaa745561679a6480747b0850593fa2c41f0cdc9
