### ISSUE TITLE
Bug in PID part ?

### ISSUE THREAD

**Issue by lpatiny** [Bioreactor/Bioreactor_v4#72]
![image](https://cloud.githubusercontent.com/assets/1484241/22396257/c44945f8-e554-11e6-83e3-d91e3977b5bd.png)

Seems strange to me that the 2 resistors are in serial no ?

**Comment by qcabrol** [comment]
Problem due to HEXFET voltage polarization >4V, use a suitable FET like IPB081N06L3GATMA1
http://www.mouser.fr/ProductDetail/Infineon-Technologies/IPB081N06L3GATMA1/?qs=sGAEpiMZZMshyDBzk1%2fWi4lI00SCTc04lxzIWulRTHY=
Or even better using a suitable IGBT (more expensive though)

**Comment by lpatiny** [comment]
We still have 2 problems in the current version.
1. we should connect both resistance (the one to the gate and the one to the led) directly to the microcontroller. Currently with 1kohms resistance we loose 0.8 volts ! The best is to directly connect both resistor to D6.
2. With IPB081 we are still outside specification or at least really at the edge.
![image](https://cloud.githubusercontent.com/assets/1484241/22617325/4518419e-eac2-11e6-933a-ea9351392fed.png)
Removing the resistance (disabling the control LED) helps but the IPB081 still reached 160°C when I push a little bit the heating plate. I guess we could survive with it for now but there should be a better solution.
