### ISSUE TITLE
Shopping Cart

### ISSUE THREAD

**Issue by qcabrol** [Bioreactor/Bioreactor_v4#73]
PowerFET operating below 3V threshold with low RDS (4mOhms):
http://www.mouser.ch/ProductDetail/NXP-Semiconductors/BUK965R8-100E118/?qs=sGAEpiMZZMshyDBzk1%2fWi735hrgcpETc3k%2fKUwf3lhI%3d

**Comment by qcabrol** [comment]
High Side power switch circuit with enhanced N-MOS 2n7002 (SOT23) to the ground followed by a MMBT4403 PNP triggering a 5.6V zener (SOD80) line

Zener Diode Choice
http://www.mouser.ch/ProductDetail/Vishay-Semiconductors/TZM5232B-GS08/?qs=sGAEpiMZZMtQ8nqTKtFS%2fC7KvLOwmmQC8eAIP5AcSGU%3d

2n7002 reference
http://www.mouser.ch/ProductDetail/ON-Semiconductor/2N7002LT1G/?qs=sGAEpiMZZMtqO%252bWUGLBzeAme2MkyyOCy

**Comment by lpatiny** [comment]
Ok I bought the IRL2505
