### ISSUE TITLE
Change resistance value for pbcheated hack

### ISSUE THREAD

**Issue by apatru** [Bioreactor/Bioreactor_v4#75]
The resistance on 12V should be changed from 1k to 100ohm. With the hack, the input of the IGBT before the 162ohm resistance is 6V.

Hack is using FMMT597TA PNP High Voltage, 2N7002 MOSFET N and zener diode of 5.6V.

**Comment by qcabrol** [comment]
Should remove the 1k (v < 4.5) and use a N-MOS technology HEXFET with low threshould eg. IRL2505 in DPAK2 package.  
Already corrected on V4.5
