### ISSUE TITLE
OneWire liquid_temp & pcb_temp freeze

### ISSUE THREAD

**Issue by apatru** [Bioreactor/Bioreactor_v4#78]
The temperature is freezing after some operation time. Need to reupload the code in order to unfreeze

**Comment by lpatiny** [comment]
What you mean is that the temperature is not updated anymore but the bioreactor continues to work ? And the low priority led blinks ?

**Comment by apatru** [comment]
when using A and/or B on the Serial, values remain the same even if it is heating more. As those values freeze under the limits, the bioreactor continues to work and the low priority led is blinking.

**Comment by lpatiny** [comment]
Seems that with the process lock it does not happen anymore
