### ISSUE TITLE
Weight measurement

### ISSUE THREAD

**Issue by apatru** [Bioreactor/Bioreactor_v4#79]
Weight measurement is jumping when stepper is ON. Shielding loading cells cables could improve that

**Comment by lpatiny** [comment]
Do you have numbers with and without shielding ? You can copy / paste a `wt` result

**Comment by apatru** [comment]
With stepper ON:
Current weight
-7491 = 753g
-7586 = 787g
-7600 = 792g
-7545 = 772g
-7521 = 764g
-7461 = 743g
-7461 = 743g
-7457 = 741g
-7453 = 740g
-7530 = 767g

With stepper OFF: 
Current weight
-7536 = 769g
-7538 = 770g
-7533 = 768g
-7539 = 770g
-7533 = 768g
-7539 = 770g
-7536 = 769g
-7526 = 766g
-7537 = 770g
-7530 = 767g

**Comment by apatru** [comment]
no shielding has been mounted yet

**Comment by lpatiny** [comment]
We circumvented the problem by checking the more stable values out of 5
